# Generated by Django 5.1.2 on 2024-11-04 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idetiqueta', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idusuario', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_usuario', models.CharField(blank=True, max_length=25, null=True)),
                ('nombre_real', models.CharField(max_length=40)),
                ('correo', models.CharField(max_length=60)),
                ('contraseña', models.CharField(max_length=16)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idimagen', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('texto_alt', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='media/')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('etiqueta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Albume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idalbum', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('duegno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.usuario')),
            ],
        ),
    ]
