# Generated by Django 5.1.2 on 2024-11-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='etiqueta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Albume',
        ),
        migrations.DeleteModel(
            name='Etiqueta',
        ),
    ]
