# Generated by Django 5.1.2 on 2024-11-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_imagen_etiqueta_delete_albume_delete_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
