# Generated by Django 5.1.2 on 2024-11-06 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_imagen_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='ultima_actualizacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ultima_actualizacion',
        ),
    ]
