# Generated by Django 5.1.2 on 2024-11-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_remove_imagen_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagen',
            name='ultima_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultima_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
